program VectArtDesigner;

uses
  VectArtDesignerPaintPreview in 'Source\ObjectProperties\Color\VectArtDesignerPaintPreview.pas',
  VectArtDesignerGradientGeometry in 'Source\Rendering\VectArtDesignerGradientGeometry.pas',
  VectArtDesignerNumericSlider in 'Source\UI\VectArtDesignerNumericSlider.pas',
  ColorPickerColorMath in 'Lib\ColorPicker\ColorPickerColorMath.pas',
  ColorPickerHueBar in 'Lib\ColorPicker\ColorPickerHueBar.pas',
  ColorPickerSVArea in 'Lib\ColorPicker\ColorPickerSVArea.pas',
  VectArtDesignerFillPaint in 'Source\Rendering\VectArtDesignerFillPaint.pas',
  VectArtDesignerMifPngMetadata in 'Source\Persistence\Mif\VectArtDesignerMifPngMetadata.pas',
  VectArtDesignerColorSwatch in 'Source\ObjectProperties\Color\VectArtDesignerColorSwatch.pas',
  VectArtDesignerSvgWriter in 'Source\Persistence\Svg\VectArtDesignerSvgWriter.pas',
  VectArtDesignerSvgPrimitives in 'Source\Persistence\Svg\VectArtDesignerSvgPrimitives.pas',
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  TextRendererSkiaBootstrap in 'Lib\TextRenderer\TextRendererSkiaBootstrap.pas',
  TextRendererTypes in 'Lib\TextRenderer\TextRendererTypes.pas',
  TextRenderer in 'Lib\TextRenderer\TextRenderer.pas',
  TextRendererSkiaRuntime in 'Lib\TextRenderer\TextRendererSkiaRuntime.pas',
  TextRendererSkia in 'Lib\TextRenderer\TextRendererSkia.pas',
  ShortcutAction in 'Lib\ShortcutAction\ShortcutAction.pas',
  HorizontalTrackBarRenderer in 'Lib\HorizontalTrackBar\HorizontalTrackBarRenderer.pas',
  HorizontalTrackBarControl in 'Lib\HorizontalTrackBar\HorizontalTrackBarControl.pas',
  VectArtDesignerMainForm in 'Source\Shell\VectArtDesignerMainForm.pas' {MainForm},
  VectArtDesignerFileActionsUI in 'Source\Shell\VectArtDesignerFileActionsUI.pas',
  VectArtDesignerEditActionsUI in 'Source\Shell\VectArtDesignerEditActionsUI.pas',
  VectArtDesignerStrokeStyleCombo in 'Source\ObjectProperties\VectArtDesignerStrokeStyleCombo.pas',
  VectArtDesignerLineToolbar in 'Source\Shell\VectArtDesignerLineToolbar.pas',
  VectArtDesignerLineStyleControls in 'Source\Shell\VectArtDesignerLineStyleControls.pas',
  VectArtDesignerCanvasSettingsDialog in 'Source\Shell\VectArtDesignerCanvasSettingsDialog.pas',
  VectArtDesignerDocument in 'Source\Core\VectArtDesignerDocument.pas',
  VectArtDesignerGeometry in 'Source\Core\VectArtDesignerGeometry.pas',
  VectArtDesignerTextGeometry in 'Source\Core\VectArtDesignerTextGeometry.pas',
  VectArtDesignerRenderer in 'Source\Rendering\VectArtDesignerRenderer.pas',
  VectArtDesignerContext in 'Source\Core\VectArtDesignerContext.pas',
  VectArtDesignerEditorState in 'Source\Core\VectArtDesignerEditorState.pas',
  VectArtDesignerEditCommands in 'Source\Core\Commands\VectArtDesignerEditCommands.pas',
  VectArtDesignerLayerStructureCommands in 'Source\Core\Commands\VectArtDesignerLayerStructureCommands.pas',
  VectArtDesignerLayerBatchCommands in 'Source\Core\Commands\VectArtDesignerLayerBatchCommands.pas',
  VectArtDesignerLayerFlipOperations in 'Source\Core\Commands\VectArtDesignerLayerFlipOperations.pas',
  VectArtDesignerLayerRotationOperations in 'Source\Core\Commands\VectArtDesignerLayerRotationOperations.pas',
  VectArtDesignerLayerVisibilityOperations in 'Source\Core\Commands\VectArtDesignerLayerVisibilityOperations.pas',
  VectArtDesignerLayerGroupOperations in 'Source\Core\Commands\VectArtDesignerLayerGroupOperations.pas',
  VectArtDesignerEditHistory in 'Source\Core\VectArtDesignerEditHistory.pas',
  VectArtDesignerMifContainer in 'Source\Persistence\Mif\VectArtDesignerMifContainer.pas',
  VectArtDesignerMifDocument in 'Source\Persistence\Mif\VectArtDesignerMifDocument.pas',
  VectArtDesignerMifDebugLog in 'Source\Persistence\Mif\VectArtDesignerMifDebugLog.pas',
  VectArtDesignerSvgDocument in 'Source\Persistence\Svg\VectArtDesignerSvgDocument.pas',
  VectArtDesignerDocumentJson in 'Source\Persistence\VectArtDesignerDocumentJson.pas',
  VectArtDesignerCanvas in 'Source\Editor\VectArtDesignerCanvas.pas',
  VectArtDesignerObjectContextMenu in 'Source\Editor\Menus\VectArtDesignerObjectContextMenu.pas',
  VectArtDesignerImageFileImport in 'Source\Editor\Import\VectArtDesignerImageFileImport.pas',
  VectArtDesignerTextEditing in 'Source\Editor\Input\VectArtDesignerTextEditing.pas',
  WindowsImeController in 'Source\Editor\Input\WindowsImeController.pas',
  VectArtDesignerSnapGeometry in 'Source\Editor\Geometry\VectArtDesignerSnapGeometry.pas',
  VectArtDesignerCanvasInteraction in 'Source\Editor\VectArtDesignerCanvasInteraction.pas',
  VectArtDesignerBezierGeometry in 'Source\Editor\Geometry\VectArtDesignerBezierGeometry.pas',
  VectArtDesignerFreehandGeometry in 'Source\Editor\Geometry\VectArtDesignerFreehandGeometry.pas',
  VectArtDesignerRoundedRectangleGeometry in 'Source\Editor\Geometry\VectArtDesignerRoundedRectangleGeometry.pas',
  VectArtDesignerShapeCreation in 'Source\Editor\VectArtDesignerShapeCreation.pas',
  VectArtDesignerKeyboardMovement in 'Source\Editor\Input\VectArtDesignerKeyboardMovement.pas',
  VectArtDesignerEditorWorkspaceFrame in 'Source\Editor\VectArtDesignerEditorWorkspaceFrame.pas',
  VectArtDesignerSelectionGeometry in 'Source\Editor\Geometry\VectArtDesignerSelectionGeometry.pas',
  VectArtDesignerSelectionOverlay in 'Source\Editor\Rendering\VectArtDesignerSelectionOverlay.pas',
  VectArtDesignerLayerList in 'Source\Layers\VectArtDesignerLayerList.pas',
  VectArtDesignerLayerRenderer in 'Source\Layers\VectArtDesignerLayerRenderer.pas',
  VectArtDesignerLayerActions in 'Source\Layers\VectArtDesignerLayerActions.pas',
  VectArtDesignerLayerOperations in 'Source\Layers\VectArtDesignerLayerOperations.pas',
  VectArtDesignerLayerDuplication in 'Source\Layers\VectArtDesignerLayerDuplication.pas',
  VectArtDesignerLayerPanelFrame in 'Source\Layers\VectArtDesignerLayerPanelFrame.pas',
  VectArtDesignerDockManager in 'Source\Layout\VectArtDesignerDockManager.pas',
  VectArtDesignerToolFrames in 'Source\Layout\VectArtDesignerToolFrames.pas',
  VectArtDesignerFillCommand in 'Source\Core\Commands\VectArtDesignerFillCommand.pas',
  VectArtDesignerAppearanceModeCommand in 'Source\Core\Commands\VectArtDesignerAppearanceModeCommand.pas',
  VectArtDesignerPaintPopup in 'Source\ObjectProperties\Color\VectArtDesignerPaintPopup.pas',
  VectArtDesignerSettingsDrafts in 'Source\ObjectProperties\VectArtDesignerSettingsDrafts.pas',
  VectArtDesignerObjectPropertiesControl in 'Source\ObjectProperties\VectArtDesignerObjectPropertiesControl.pas',
  VectArtDesignerObjectPropertiesFrame in 'Source\ObjectProperties\VectArtDesignerObjectPropertiesFrame.pas',
  VectArtDesignerToolPaletteFrame in 'Source\ToolPalette\VectArtDesignerToolPaletteFrame.pas',
  VectArtDesignerTemplateGeometry in 'Source\Editor\Geometry\VectArtDesignerTemplateGeometry.pas',
  VectArtDesignerTemplatePicker in 'Source\ToolPalette\VectArtDesignerTemplatePicker.pas',
  VectArtDesignerToolPalette in 'Source\ToolPalette\VectArtDesignerToolPalette.pas';

{$R *.res}

begin
  Application.Initialize;
  TStyleManager.TrySetStyle('Windows Modern Dark');
  Application.MainFormOnTaskbar := True;
  Application.Title := 'VectArtDesigner';
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
