program VectArtDesigner;

uses
  VectArtDesignerSettingsGeometry in 'Source\Core\Commands\Geometry\VectArtDesignerSettingsGeometry.pas',
  VectArtDesignerSettingsSelection in 'Source\Core\Selection\VectArtDesignerSettingsSelection.pas',
  VectArtDesignerCreationColors in 'Source\ToolPalette\VectArtDesignerCreationColors.pas',
  VectArtDesignerSvgPaintReader in 'Source\Persistence\Svg\Paint\VectArtDesignerSvgPaintReader.pas',
  VectArtDesignerTextureImage in 'Source\Persistence\VectArtDesignerTextureImage.pas',
  VectArtDesignerMifReader in 'Source\Persistence\Mif\VectArtDesignerMifReader.pas',
  VectArtDesignerMifPlacement in 'Source\Persistence\Mif\Rendering\VectArtDesignerMifPlacement.pas',
  VectArtDesignerMifRaster in 'Source\Persistence\Mif\Rendering\VectArtDesignerMifRaster.pas',
  VectArtDesignerMifPaint in 'Source\Persistence\Mif\Rendering\VectArtDesignerMifPaint.pas',
  VectArtDesignerSvgPaintWriter in 'Source\Persistence\Svg\Paint\VectArtDesignerSvgPaintWriter.pas',
  VectArtDesignerGradientShaders in 'Source\Rendering\Paint\VectArtDesignerGradientShaders.pas',
  VectArtDesignerPaintPreview in 'Source\ObjectProperties\Color\VectArtDesignerPaintPreview.pas',
  VectArtDesignerGradientGeometry in 'Source\Rendering\Paint\VectArtDesignerGradientGeometry.pas',
  VectArtDesignerSettingsFont in 'Source\UI\VectArtDesignerSettingsFont.pas',
  VectArtDesignerNumericSlider in 'Source\UI\VectArtDesignerNumericSlider.pas',
  ColorPickerColorMath in 'Lib\ColorPicker\ColorPickerColorMath.pas',
  ColorPickerHueBar in 'Lib\ColorPicker\ColorPickerHueBar.pas',
  ColorPickerSVArea in 'Lib\ColorPicker\ColorPickerSVArea.pas',
  VectArtDesignerFillPaint in 'Source\Rendering\Paint\VectArtDesignerFillPaint.pas',
  VectArtDesignerMifPngMetadata in 'Source\Persistence\Mif\VectArtDesignerMifPngMetadata.pas',
  VectArtDesignerColorSwatch in 'Source\ObjectProperties\Color\VectArtDesignerColorSwatch.pas',
  VectArtDesignerSvgWriter in 'Source\Persistence\Svg\VectArtDesignerSvgWriter.pas',
  VectArtDesignerSvgPrimitives in 'Source\Persistence\Svg\VectArtDesignerSvgPrimitives.pas',
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  TextRendererSkiaBootstrap in 'Lib\TextRenderer\TextRendererSkiaBootstrap.pas',
  TextRendererTypes in 'Lib\TextRenderer\TextRendererTypes.pas',
  TextRenderer in 'Lib\TextRenderer\TextRenderer.pas',
  TextRendererSkiaRuntime in 'Lib\TextRenderer\TextRendererSkiaRuntime.pas',
  TextRendererSkia in 'Lib\TextRenderer\TextRendererSkia.pas',
  ShortcutAction in 'Lib\ShortcutAction\ShortcutAction.pas',
  HorizontalTrackBarRenderer in 'Lib\HorizontalTrackBar\HorizontalTrackBarRenderer.pas',
  HorizontalTrackBarControl in 'Lib\HorizontalTrackBar\HorizontalTrackBarControl.pas',
  VerticalScrollBarControl in 'Lib\VerticalScrollBar\VerticalScrollBarControl.pas',
  VectArtDesignerMainForm in 'Source\Shell\VectArtDesignerMainForm.pas' {MainForm},
  VectArtDesignerDocumentSession in 'Source\Shell\Document\VectArtDesignerDocumentSession.pas',
  VectArtDesignerFileActionsUI in 'Source\Shell\VectArtDesignerFileActionsUI.pas',
  VectArtDesignerDocumentFileController in 'Source\Shell\File\VectArtDesignerDocumentFileController.pas',
  VectArtDesignerRecentFiles in 'Source\Shell\File\VectArtDesignerRecentFiles.pas',
  VectArtDesignerEditActionsUI in 'Source\Shell\VectArtDesignerEditActionsUI.pas',
  VectArtDesignerStrokeStyleCombo in 'Source\ObjectProperties\VectArtDesignerStrokeStyleCombo.pas',
  VectArtDesignerLineToolbar in 'Source\Shell\VectArtDesignerLineToolbar.pas',
  VectArtDesignerLineStyleControls in 'Source\Shell\VectArtDesignerLineStyleControls.pas',
  VectArtDesignerCanvasSettingsDialog in 'Source\Shell\VectArtDesignerCanvasSettingsDialog.pas',
  VectArtDesignerObjectAttributes in 'Source\Core\Appearance\VectArtDesignerObjectAttributes.pas',
  VectArtDesignerShadowPaint in 'Source\Rendering\Paint\VectArtDesignerShadowPaint.pas',
  VectArtDesignerMifShadow in 'Source\Persistence\Mif\Rendering\VectArtDesignerMifShadow.pas',
  VectArtDesignerShadowCommand in 'Source\Core\Commands\Appearance\VectArtDesignerShadowCommand.pas',
  VectArtDesignerShadowSettings in 'Source\ObjectProperties\Pages\VectArtDesignerShadowSettings.pas',
  VectArtDesignerSvgShadow in 'Source\Persistence\Svg\Paint\VectArtDesignerSvgShadow.pas',
  VectArtDesignerSettingsSections in 'Source\ObjectProperties\Pages\VectArtDesignerSettingsSections.pas',
  VectArtDesignerDocument in 'Source\Core\VectArtDesignerDocument.pas',
  VectArtDesignerLayerDataTransfer in 'Source\Core\Transfer\VectArtDesignerLayerDataTransfer.pas',
  VectArtDesignerGeometry in 'Source\Core\VectArtDesignerGeometry.pas',
  VectArtDesignerTextGeometry in 'Source\Core\VectArtDesignerTextGeometry.pas',
  VectArtDesignerRenderer in 'Source\Rendering\VectArtDesignerRenderer.pas',
  VectArtDesignerContext in 'Source\Core\VectArtDesignerContext.pas',
  VectArtDesignerEditorState in 'Source\Core\VectArtDesignerEditorState.pas',
  VectArtDesignerEditCommands in 'Source\Core\Commands\VectArtDesignerEditCommands.pas',
  VectArtDesignerLayerStructureCommands in 'Source\Core\Commands\Structure\VectArtDesignerLayerStructureCommands.pas',
  VectArtDesignerLayerBatchCommands in 'Source\Core\Commands\VectArtDesignerLayerBatchCommands.pas',
  VectArtDesignerLayerAlignmentOperations in 'Source\Core\Commands\Transform\VectArtDesignerLayerAlignmentOperations.pas',
  VectArtDesignerLayerFlipOperations in 'Source\Core\Commands\Transform\VectArtDesignerLayerFlipOperations.pas',
  VectArtDesignerLayerRotationOperations in 'Source\Core\Commands\Transform\VectArtDesignerLayerRotationOperations.pas',
  VectArtDesignerLayerVisibilityOperations in 'Source\Core\Commands\Structure\VectArtDesignerLayerVisibilityOperations.pas',
  VectArtDesignerLayerGroupOperations in 'Source\Core\Commands\Structure\VectArtDesignerLayerGroupOperations.pas',
  VectArtDesignerEditHistory in 'Source\Core\VectArtDesignerEditHistory.pas',
  VectArtDesignerMifContainer in 'Source\Persistence\Mif\VectArtDesignerMifContainer.pas',
  VectArtDesignerMifDocument in 'Source\Persistence\Mif\VectArtDesignerMifDocument.pas',
  VectArtDesignerMifDebugLog in 'Source\Persistence\Mif\VectArtDesignerMifDebugLog.pas',
  VectArtDesignerSvgDocument in 'Source\Persistence\Svg\VectArtDesignerSvgDocument.pas',
  VectArtDesignerDocumentJson in 'Source\Persistence\VectArtDesignerDocumentJson.pas',
  VectArtDesignerClipboardOperations in 'Source\Editor\Clipboard\VectArtDesignerClipboardOperations.pas',
  VectArtDesignerAttributePasteOperations in 'Source\Editor\Clipboard\VectArtDesignerAttributePasteOperations.pas',
  VectArtDesignerCutoutSelection in 'Source\Editor\Clipboard\VectArtDesignerCutoutSelection.pas',
  VectArtDesignerCanvas in 'Source\Editor\VectArtDesignerCanvas.pas',
  VectArtDesignerObjectContextMenu in 'Source\Editor\Menus\VectArtDesignerObjectContextMenu.pas',
  VectArtDesignerImageFileImport in 'Source\Editor\Import\VectArtDesignerImageFileImport.pas',
  VectArtDesignerTextEditing in 'Source\Editor\Input\VectArtDesignerTextEditing.pas',
  WindowsImeController in 'Source\Editor\Input\WindowsImeController.pas',
  VectArtDesignerSnapGeometry in 'Source\Editor\Geometry\VectArtDesignerSnapGeometry.pas',
  VectArtDesignerCanvasInteraction in 'Source\Editor\VectArtDesignerCanvasInteraction.pas',
  VectArtDesignerBezierGeometry in 'Source\Editor\Geometry\VectArtDesignerBezierGeometry.pas',
  VectArtDesignerFreehandGeometry in 'Source\Editor\Geometry\VectArtDesignerFreehandGeometry.pas',
  VectArtDesignerRoundedRectangleGeometry in 'Source\Editor\Geometry\VectArtDesignerRoundedRectangleGeometry.pas',
  VectArtDesignerShapeCreation in 'Source\Editor\VectArtDesignerShapeCreation.pas',
  VectArtDesignerKeyboardMovement in 'Source\Editor\Input\VectArtDesignerKeyboardMovement.pas',
  VectArtDesignerEditorWorkspaceFrame in 'Source\Editor\VectArtDesignerEditorWorkspaceFrame.pas',
  VectArtDesignerSelectionGeometry in 'Source\Editor\Geometry\VectArtDesignerSelectionGeometry.pas',
  VectArtDesignerSelectionOverlay in 'Source\Editor\Rendering\VectArtDesignerSelectionOverlay.pas',
  VectArtDesignerLayerList in 'Source\Layers\VectArtDesignerLayerList.pas',
  VectArtDesignerLayerDragDrop in 'Source\Layers\Interaction\VectArtDesignerLayerDragDrop.pas',
  VectArtDesignerLayerRenderer in 'Source\Layers\VectArtDesignerLayerRenderer.pas',
  VectArtDesignerLayerActions in 'Source\Layers\VectArtDesignerLayerActions.pas',
  VectArtDesignerLayerOperations in 'Source\Layers\VectArtDesignerLayerOperations.pas',
  VectArtDesignerLayerDuplication in 'Source\Layers\VectArtDesignerLayerDuplication.pas',
  VectArtDesignerLayerPanelFrame in 'Source\Layers\VectArtDesignerLayerPanelFrame.pas',
  VectArtDesignerDockManager in 'Source\Layout\VectArtDesignerDockManager.pas',
  VectArtDesignerToolFrames in 'Source\Layout\VectArtDesignerToolFrames.pas',
  VectArtDesignerFillCommand in 'Source\Core\Commands\Appearance\VectArtDesignerFillCommand.pas',
  VectArtDesignerAppearanceModeCommand in 'Source\Core\Commands\Appearance\VectArtDesignerAppearanceModeCommand.pas',
  VectArtDesignerPaintPopup in 'Source\ObjectProperties\Color\VectArtDesignerPaintPopup.pas',
  VectArtDesignerSettingsDrafts in 'Source\ObjectProperties\Pages\VectArtDesignerSettingsDrafts.pas',
  VectArtDesignerObjectPropertiesControl in 'Source\ObjectProperties\VectArtDesignerObjectPropertiesControl.pas',
  VectArtDesignerObjectPropertiesFrame in 'Source\ObjectProperties\VectArtDesignerObjectPropertiesFrame.pas',
  VectArtDesignerToolPaletteFrame in 'Source\ToolPalette\VectArtDesignerToolPaletteFrame.pas',
  VectArtDesignerTemplatePanelFrame in 'Source\ToolPalette\VectArtDesignerTemplatePanelFrame.pas',
  VectArtDesignerTemplateGeometry in 'Source\Editor\Geometry\VectArtDesignerTemplateGeometry.pas',
  VectArtDesignerTemplatePicker in 'Source\ToolPalette\VectArtDesignerTemplatePicker.pas',
  VectArtDesignerToolPalette in 'Source\ToolPalette\VectArtDesignerToolPalette.pas';

{$R *.res}

begin
  Application.Initialize;
  TStyleManager.TrySetStyle('Windows Modern Dark');
  Application.MainFormOnTaskbar := True;
  Application.Title := 'VectArtDesigner';
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;
end.
